repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^templates/
      - id: trailing-whitespace
        exclude: ^templates/
      - id: check-yaml
        exclude: ^templates/
      - id: check-added-large-files
        exclude: uv\.lock$

  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^templates/

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.0
    hooks:
      - id: isort
        name: isort (python)
        exclude: ^templates/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^templates/
      - id: ruff-format
        exclude: ^templates/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests"]
        exclude: ^templates/
